Input: add the driver for NextWindow touchscreens (v2)
Copy the code from https://github.com/DadaMonad/nwfermi
commit 63d7fd5071b9c8e6937a6d5d186d1d689641b99b with cosmetics.

(v2) Fixes the following building error:

  MODPOST Module.symvers
ERROR: modpost: missing MODULE_DESCRIPTION() in drivers/input/touchscreen/nw-fermi.o