ANDROID: sdcardfs: make helpers idmap mount aware (v2)
Additional changes due to commit 549c729 ("fs: make helpers idmap mount aware")

Fixes the following building errors happening when building kernel with clang,
so the changes are necessary also for correct build of kernel with gcc

/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:796:17: error: incompatible function pointer types initializi
ng 'int (*)(struct vfsmount *, struct user_namespace *, struct inode *, int)' with an expression of type 'int (str
uct vfsmount *, struct inode *, int)' [-Werror,-Wincompatible-function-pointer-types]
        .permission2    = sdcardfs_permission,
                          ^~~~~~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:797:14: error: incompatible function pointer types initializi
ng 'int (*)(struct vfsmount *, struct user_namespace *, struct dentry *, struct iattr *)' with an expression of ty
pe 'int (struct vfsmount *, struct dentry *, struct iattr *)' [-Werror,-Wincompatible-function-pointer-types]
        .setattr2       = sdcardfs_setattr,
                          ^~~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:808:13: error: incompatible function pointer types initializi
ng 'int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t, bool)' (aka 'int (*)(struct user_na
mespace *, struct inode *, struct dentry *, unsigned short, _Bool)') with an expression of type 'int (struct inode
 *, struct dentry *, umode_t, bool)' (aka 'int (struct inode *, struct dentry *, unsigned short, _Bool)') [-Werror
,-Wincompatible-function-pointer-types]
        .create         = sdcardfs_create,
                          ^~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:810:16: error: incompatible function pointer types initializi
ng 'int (*)(struct user_namespace *, struct inode *, int)' with an expression of type 'int (struct inode *, int)'
[-Werror,-Wincompatible-function-pointer-types]
        .permission     = sdcardfs_permission_wrn,
                          ^~~~~~~~~~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:811:17: error: incompatible function pointer types initializi
ng 'int (*)(struct vfsmount *, struct user_namespace *, struct inode *, int)' with an expression of type 'int (str
uct vfsmount *, struct inode *, int)' [-Werror,-Wincompatible-function-pointer-types]
        .permission2    = sdcardfs_permission,
                          ^~~~~~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:813:12: error: incompatible function pointer types initializi
ng 'int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t)' (aka 'int (*)(struct user_namespac
e *, struct inode *, struct dentry *, unsigned short)') with an expression of type 'int (struct inode *, struct de
ntry *, umode_t)' (aka 'int (struct inode *, struct dentry *, unsigned short)') [-Werror,-Wincompatible-function-p
ointer-types]
        .mkdir          = sdcardfs_mkdir,
                          ^~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:815:13: error: incompatible function pointer types initializi
ng 'int (*)(struct user_namespace *, struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned in
t)' with an expression of type 'int (struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned in
t)' [-Werror,-Wincompatible-function-pointer-types]
        .rename         = sdcardfs_rename,
                          ^~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:816:13: error: incompatible function pointer types initializi
ng 'int (*)(struct user_namespace *, struct dentry *, struct iattr *)' with an expression of type 'int (struct den
try *, struct iattr *)' [-Werror,-Wincompatible-function-pointer-types]
        .setattr        = sdcardfs_setattr_wrn,
                          ^~~~~~~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:817:14: error: incompatible function pointer types initializi
ng 'int (*)(struct vfsmount *, struct user_namespace *, struct dentry *, struct iattr *)' with an expression of ty
pe 'int (struct vfsmount *, struct dentry *, struct iattr *)' [-Werror,-Wincompatible-function-pointer-types]
        .setattr2       = sdcardfs_setattr,
                          ^~~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:818:13: error: incompatible function pointer types initializi
ng 'int (*)(struct user_namespace *, const struct path *, struct kstat *, u32, unsigned int)' (aka 'int (*)(struct
 user_namespace *, const struct path *, struct kstat *, unsigned int, unsigned int)') with an expression of type '
int (const struct path *, struct kstat *, u32, unsigned int)' (aka 'int (const struct path *, struct kstat *, unsi
gned int, unsigned int)') [-Werror,-Wincompatible-function-pointer-types]
        .getattr        = sdcardfs_getattr,
                          ^~~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:822:16: error: incompatible function pointer types initializi
ng 'int (*)(struct user_namespace *, struct inode *, int)' with an expression of type 'int (struct inode *, int)'
[-Werror,-Wincompatible-function-pointer-types]
        .permission     = sdcardfs_permission_wrn,
                          ^~~~~~~~~~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:823:17: error: incompatible function pointer types initializi
ng 'int (*)(struct vfsmount *, struct user_namespace *, struct inode *, int)' with an expression of type 'int (str
uct vfsmount *, struct inode *, int)' [-Werror,-Wincompatible-function-pointer-types]
        .permission2    = sdcardfs_permission,
                          ^~~~~~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:824:13: error: incompatible function pointer types initializi
ng 'int (*)(struct user_namespace *, struct dentry *, struct iattr *)' with an expression of type 'int (struct den
try *, struct iattr *)' [-Werror,-Wincompatible-function-pointer-types]
        .setattr        = sdcardfs_setattr_wrn,
                          ^~~~~~~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:825:14: error: incompatible function pointer types initializi
ng 'int (*)(struct vfsmount *, struct user_namespace *, struct dentry *, struct iattr *)' with an expression of ty
pe 'int (struct vfsmount *, struct dentry *, struct iattr *)' [-Werror,-Wincompatible-function-pointer-types]
        .setattr2       = sdcardfs_setattr,
                          ^~~~~~~~~~~~~~~~
/home/utente/s-x86_kernel/kernel/fs/sdcardfs/inode.c:826:13: error: incompatible function pointer types initializi
ng 'int (*)(struct user_namespace *, const struct path *, struct kstat *, u32, unsigned int)' (aka 'int (*)(struct
 user_namespace *, const struct path *, struct kstat *, unsigned int, unsigned int)') with an expression of type '
int (const struct path *, struct kstat *, u32, unsigned int)' (aka 'int (const struct path *, struct kstat *, unsi
gned int, unsigned int)') [-Werror,-Wincompatible-function-pointer-types]
        .getattr        = sdcardfs_getattr,
                          ^~~~~~~~~~~~~~~~
15 errors generated.

Change-Id: Ie45289865dba283bee848209cca43e90a84189aa