android: ashmem: use vm_flags_clear() helper function
Changes due to commit bc292ab ("mm: introduce vma->vm_flags wrapper functions")

Fixes the following building error:

/home/utente/r-x86_kernel/kernel/drivers/staging/android/ashmem.c:404:16: error: cannot assign to non-static data member 'vm_flags
' with const-qualified type 'const vm_flags_t' (aka 'const unsigned long')
        vma->vm_flags &= ~calc_vm_may_flags(~asma->prot_mask);
        ~~~~~~~~~~~~~ ^
/home/utente/r-x86_kernel/kernel/include/linux/mm_types.h:500:20: note: non-static data member 'vm_flags' declared const here
                const vm_flags_t vm_flags;
                ~~~~~~~~~~~~~~~~~^~~~~~~~
1 error generated.