ANDROID: netfilter: xt_qtaguid: add qtaguid matching module (v3)
(v3) Replace atomic_long_read(&el_socket->file->f_count) with file_ref_read(&el_socket->file->f_ref)
     due to kernel commit 90ee6ed776c0 "fs: port files to file_ref"

Fixes the following building error:

./kernel/net/netfilter/xt_qtaguid.c:2383:46: error: no member named 'f_count' in 'struct file'
                 input, atomic_long_read(&el_socket->file->f_count),
                                          ~~~~~~~~~~~~~~~  ^
1 error generated.