x86: add driver for Lenovo ideapad S10-3T rotate button (v2)
Provided by Javier S. Pedro.

(v2)
Changes due to following commits:
79a56f4 "platform/x86: wmi: Remove wmi_get_event_data()"
e04e2b7 "platform/x86: wmi: Pass event data directly to legacy notify handlers"

Fixes the following building errors:

./kernel/drivers/platform/x86/lsrot.c:134:11: error: implicit declaration of function 'wmi_get_event_data' is invalid in C9
9 [-Werror,-Wimplicit-function-declaration]
        status = wmi_get_event_data(value, &response);
                 ^
  CC [M]  drivers/staging/rtl8723bs/hal/HalHWImg8723B_MAC.o
./kernel/drivers/platform/x86/lsrot.c:206:38: error: incompatible function pointer types passing 'void (u32, void *)' (aka
'void (unsigned int, void *)') to parameter of type 'wmi_notify_handler' (aka 'void (*)(union acpi_object *, void *)') [-Werror,-Wincompatible-func
tion-pointer-types]
                                            event_handler, NULL);
                                            ^~~~~~~~~~~~~
./kernel/include/linux/acpi.h:404:25: note: passing argument to parameter 'handler' here
                                        wmi_notify_handler handler, void *data);
                                                           ^
2 errors generated.