android: ashmem: use shrinker_register() instead of register_shrinker()
Changes due to commit f2383e01507 ("mm: shrinker: remove old APIs")

Fixes the following building errors:

./kernel/drivers/staging/android/ashmem.c:951:18: error: assigning to 'struct shrinker' from incompatible type 'struct shrinker *'; dereference with *
        ashmem_shrinker = shrinker_alloc(0, "android-ashmem");
                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                          *
./kernel/drivers/staging/android/ashmem.c:952:6: error: invalid argument type 'struct shrinker' to unary expression
        if (!ashmem_shrinker) {
            ^~~~~~~~~~~~~~~~
./kernel/drivers/staging/android/ashmem.c:957:20: error: passing 'struct shrinker' to parameter of incompatible type
'struct shrinker *'; take the address with &
        shrinker_register(ashmem_shrinker);
                          ^~~~~~~~~~~~~~~
                          &
./kernel/include/linux/shrinker.h:136:41: note: passing argument to parameter 'shrinker' here
void shrinker_register(struct shrinker *shrinker);
                                        ^
3 errors generated.

./kernel/drivers/staging/android/ashmem.c:951:8: error: implicit declaration of function 'register_shrinker' is inval
id in C99 [-Werror,-Wimplicit-function-declaration]
        ret = register_shrinker(&ashmem_shrinker, "android-ashmem");
              ^
./kernel/drivers/staging/android/ashmem.c:951:8: note: did you mean 'register_chrdev'?
./kernel/include/linux/fs.h:2624:19: note: 'register_chrdev' declared here
static inline int register_chrdev(unsigned int major, const char *name,
                  ^
1 error generated.

./kernel/drivers/staging/android/ashmem.c:851:30: error: incompatible pointer types passing 'struct shrinker **' to p
arameter of type 'struct shrinker *'; remove & [-Werror,-Wincompatible-pointer-types]
                        ret = ashmem_shrink_count(&ashmem_shrinker, &sc);
                                                  ^~~~~~~~~~~~~~~~
./kernel/drivers/staging/android/ashmem.c:520:38: note: passing argument to parameter 'shrink' here
ashmem_shrink_count(struct shrinker *shrink, struct shrink_control *sc)
                                     ^
./kernel/drivers/staging/android/ashmem.c:852:23: error: incompatible pointer types passing 'struct shrinker **' to p
arameter of type 'struct shrinker *'; remove & [-Werror,-Wincompatible-pointer-types]
                        ashmem_shrink_scan(&ashmem_shrinker, &sc);
                                           ^~~~~~~~~~~~~~~~
./kernel/drivers/staging/android/ashmem.c:478:37: note: passing argument to parameter 'shrink' here
ashmem_shrink_scan(struct shrinker *shrink, struct shrink_control *sc)
                                    ^
2 errors generated.