staging: android: use mm_get_unmapped_area() in ashmem
Changes due to commit 529ce23 ("mm: switch mm->get_unmapped_area() to a flag")

Fixes the following building error:

./kernel/drivers/staging/android/ashmem.c:375:22: error: no member named 'get_unmapped_area' in 'struct mm_struct'
        return current->mm->get_unmapped_area(file, addr, len, pgoff, flags);
               ~~~~~~~~~~~  ^
1 error generated.