staging: android: update shmem_file_setup() to use vma_flags_t
Temporary build fix which is relying on revert of commit
53f1d936445 ("mm: make vm_area_desc utilise vma_flags_t only")

Fixes the following building error:

./kernel/drivers/staging/android/ashmem.c:415:47: error: passing 'const vm_flags_t' (aka 'const unsigned long') to parameter of inc
ompatible type 'vma_flags_t'
                vmfile = shmem_file_setup(name, asma->size, vma->vm_flags);
                                                            ^~~~~~~~~~~~~
./kernel/include/linux/shmem_fs.h:105:74: note: passing argument to parameter 'flags' here
struct file *shmem_file_setup(const char *name, loff_t size, vma_flags_t flags);
                                                                         ^
  CC [M]  drivers/platform/chrome/cros_ec_lightbar.o
1 error generated.