staging: rtl8723bu: fix undefined __divdi3 in 32bit builds
Fix the following building error in 32bit builds by using do_div()

ERROR: "__divdi3" [drivers/staging/rtl8723bu/8723bu.ko] undefined!

The code causing the issue was identified doing:
objdump -x output to find the offset of __divdi3
objdump -d output to find the surroundings of __divdi3 call

The problem was in rtw_get_systime_us() function

Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>