android: ashmem: provide shrinker with name
Change due to commit e33c267ab70 ("mm: shrinkers: provide shrinkers with names")

Fixes the following building error:

./kernel/drivers/staging/android/ashmem.c:951:42: error: too few arguments to function call, expected at least 2, have 1
        ret = register_shrinker(&ashmem_shrinker);
              ~~~~~~~~~~~~~~~~~                 ^
/media/bigblissdrive/t-x86/kernel/include/linux/shrinker.h:99:27: note: 'register_shrinker' declared here
extern int __printf(2, 3) register_shrinker(struct shrinker *shrinker,
                          ^
1 error generated.